### ISSUE TITLE
6.4.0 release status

### ISSUE THREAD

**Issue by sgoger** [thumbor/thumbor#1023]
### Thumbor request URL
https://github.com/thumbor/thumbor/releases

We'd like to see a 6.4.0 release happening soon. Here's a quick checklist of things to do until a release can be considered by maintainers.

### Checklist:
- [x] Get it running in a controlled environment.
- [x] Test most common usage (see doc)
- [x] Manually test issues/PR merged into master since 6.3.2
- [x] If necessary add integration tests for issues/PRs merged into master since 6.3.2
- [ ] Fix unit tests on master (see [comment below](https://github.com/thumbor/thumbor/issues/1023#issuecomment-355935619))
- [x] All the new features are well tested & documented
- [x] All the bugs fixed can't be reproduced
- [x] Change the version in setup.py (#1029)
- [x] Update the CHANGELOG (#1029)

**Comment by heynemann** [comment]
Great job guys!!! I'm so proud of the community around thumbor. Sorry for not being able to put more effort into it.

**Comment by Kmaschta** [comment]
Hi guys, I'm on it! You can check the first item of the list.

Here are the [PR merged & other commits since the previous release](https://github.com/thumbor/thumbor/compare/6.3.2...master).
I'm going to do a triage (with Features, Bugs, etc). That's huge!

<details>
 <summary>Project history since previous release</summary>

- #877 fixing issue with full-fit-in and requested width/height (Savar)
- #883 fix exception with smart detection + gif + meta endpoint (Savar)
- #892 using the content detection to determine extension (Savar)
- #890 resizing the watermark relative to image [fixes #874] (Savar)
- #905 Add manual garbage collection to free memory (okor)
- #878 adding new filter `upscale()` [fixes #726 and #856] (Savar)
- #908 added new timeout setting if using curl http client (Savar)
- #907 Add background_color option to gifv (okor)
- #901 Fix race condition for preserving exif data (mb-m)
- #902 Jpegtran should preserve ICC profile if not forced to strip (kkopachev)
- #931 Update Pillow to version 4 (kkopachev)
- #753 Fix Memory Usage Explosion (SergioJorge)
- **Release Candidate 6.3.3rc**
- #940 Add new strip_exif filter in order to remove exif on demand (franek)
- #947 Fix typos in the documentation (crowchirp)
- #953 Add convenience links to docs in README.mkd (combs)
- #928 Allow custom LoaderResult errors (gi11es)
- #958 CHANGELOG: add 5.0.5 to 6.3.2 from GitHub releases (pda)
- ~#952 Git Shallow Clone on CI w/ other changes (raphamorim)~ [reverted]
- #948 print(), xrange(), unicode(), basestring, exception changes for Python 3 (raphamorim)
- #960 Remove Python 2.6 from documentation (cclauss)
- #961 Define unicode() for Python 3 (cclauss)
- #963 Add options to allow header forwarding for the HTTP_Loader (asvinours)
- #887 fixing _composite.apply with bigger source images (Savar)
- #886 resync BaseEngine with existing implementations (Savar)
- #890 resizing the watermark relative to image [fixes #874] (Savar)
- #973 Remove IGNORE_DECODING_ERRORS constant (homm)
- #975 Travis: Improve build time (marcelometal)
- #977 Remove debian folder(marcelometal)
- #970 Travis: Added lint test (marcelometal)
- #982 Replaced 'pexif' dependency with 'piexif' (marcelometal)
- #981 Docs: Fixed getting started (marcelometal)
- #983 Fixed urllib Python 2 and 3 compatibility (marcelometal)
- 98d90b030299dafcdf253547567152e8a8df110c New red eye filter based on cv2/cv3 (kkopachev)
- 1d5ecf1a9825f3d8b094c3cf0965204f76a74172 Update noise filter test image to be png, so SSIM will work (kkopachev)
- 58d4bb979e678a469f9032c13107b08a03147146 Fix resize causing transparency loss on paletted images [fixes #987 #945 #943] (kkopachev)
- #974 Updates for Travis: new python (kkopachev)
- #995 Fix transformer tests and fix exception thrown when fit-in + requested size has "orig" (kkopachev)
- #997 Fix 500 with watermark on S3 [fixes #996] (gingerlime)
- #1014 Some minor updates to the docs (tomsaleeba)
- f163acee1a274eff2e0821d250af0afed7f854f9 Fixed reorientate tests for big endian machines (marcelometal)

</details>

**Comment by Kmaschta** [comment]
I'm not sure if I'll be able to test the whole thing, but what about release a `6.4.0rc` version ?

I'll try to list all the stuff to do before the release right there:

- [ ] Fix unit tests on master
- [x] All the new features are well tested & documented (unless #905 perhaps)
- [ ] All the bugs fixed can't be reproduced (testing in progress)

**Comment by Kmaschta** [comment]
To me, the release looks good, but I can't fix the 3 tests that fail on master:

```
======================================================================
FAIL: test_with_four_images (tests.filters.test_distributed_collage.DistributedCollageFilterTestCase)
----------------------------------------------------------------------
AssertionError: Expected topic(0.85308648129474507) to be greater than 0.89
======================================================================
FAIL: test_with_three_images (tests.filters.test_distributed_collage.DistributedCollageFilterTestCase)
----------------------------------------------------------------------
AssertionError: Expected topic(0.8977135521263041) to be greater than 0.98
======================================================================
FAIL: test_with_two_images (tests.filters.test_distributed_collage.DistributedCollageFilterTestCase)
----------------------------------------------------------------------
AssertionError: Expected topic(0.84592690789752267) to be greater than 0.98
```
I wasn't able to find the commit that breaks them. I suspect a faulty dependency upgrade.

**Comment by heynemann** [comment]
Thank you so much @Kmaschta. Great job. I hope @scorphus can check this out soon, as this filter is not even documented :(

**Comment by sgoger** [comment]
@heynemann I've updated the ticket description to add @Kmaschta's checklist. We've now got only one check left. Let's hope we can check this one quickly and proceed with a 6.4 release 😃

**Comment by Savar** [comment]
@Kmaschta it seems to be a dependency issue on something.. I can try with 2 different Dockerfiles and one time it's broken, the other it is not.. I try to check deeper if I find more info but cannot promise anything

**Comment by heynemann** [comment]
The distributed collage has been removed from the codebase and moved to https://github.com/globocom/thumbor-distributed-collage-filter. This release is good to go!

**Comment by marcelometal** [comment]
Done! 

Ref: 145ef882a703df323ab656cdbd5381435554d6b6

**Comment by heynemann** [comment]
Release Notes: https://github.com/thumbor/thumbor/releases/tag/v6.4.0
PyPi: https://pypi.python.org/pypi/thumbor/6.4.0
